# Enable container based builds
sudo: required
language: python

services:
  - docker
  
env:
  AWS_DEFAULT_REGION: us-east-1

python:
  - "2.7"
  - "3.6"

install:
  # Install the code requirements
  - make init

# Install Docs requirements

script:
  # Runs unit tests
  - make integ-test
